server:
  port: 8081
spring:
  profiles:
    active: dev

jasypt:
  encryptor:
    password: e!swhdg&d763jo

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 153624
    url: jdbc:mysql://localhost:3306/surpass?useUnicode=true&characterEncoding=utf-8&useSSL=false
    platform: mysql
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: always
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis